# Generated by Django 5.2.9 on 2026-07-24 11:25

import django.db.models.deletion
import django.utils.timezone
import mro_app.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PartIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_order_no', models.CharField(db_index=True, max_length=100)),
                ('serial_number', models.CharField(db_index=True, max_length=100)),
                ('tracking_no', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('customer', models.CharField(blank=True, max_length=200, null=True)),
                ('qty', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('not started', 'Not Started'), ('in progress', 'In Progress'), ('rejected', 'Rejected'), ('waiting', 'Waiting'), ('completed', 'Completed'), ('delivered', 'Delivered')], default='not started', max_length=20)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='part_qrcodes/')),
                ('is_delivered', models.BooleanField(default=False)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('is_warranty_claim', models.BooleanField(default=False, verbose_name='Is Warranty?')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason_of_removal', models.TextField(blank=True, null=True)),
                ('is_audit_approved', models.BooleanField(default=False, verbose_name='approved')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to=mro_app.models.get_file_path)),
                ('repair_completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('rejection_date', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='my_assigned_parts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PartInLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('part_in', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='mro_app.partin')),
            ],
        ),
        migrations.CreateModel(
            name='PartMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(choices=[('Official', 'Official'), ('non-Official', 'non-Official')], default='Official', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='partin',
            name='part_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='mro_app.partmaster'),
        ),
        migrations.CreateModel(
            name='StatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('part_in', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='mro_app.partin')),
            ],
        ),
    ]
