# Generated by Django 5.1.3 on 2025-12-27 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Tamo", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="partin",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="Entry Date"
            ),
        ),
    ]
