# Generated by Django 5.1.3 on 2025-12-27 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Tamo", "0002_partin_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="partin",
            name="tracking_no",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
