# Generated by Django 5.1.3 on 2026-01-01 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Tamo", "0003_alter_partin_tracking_no"),
    ]

    operations = [
        migrations.AddField(
            model_name="partin",
            name="reason_of_removal",
            field=models.TextField(
                blank=True, null=True, verbose_name="Reason of Removal"
            ),
        ),
        migrations.AlterField(
            model_name="partin",
            name="created_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Entry Date"
            ),
        ),
    ]
