# Generated by Django 5.1.3 on 2026-01-02 17:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Tamo", "0005_statushistory"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="partin",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="my_assigned_parts",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Person in Charge",
            ),
        ),
        migrations.AlterField(
            model_name="partin",
            name="status",
            field=models.CharField(
                choices=[
                    ("not started", "Not Started"),
                    ("in progress", "In Progress"),
                    ("rejected", "Rejected"),
                    ("waiting", "Waiting"),
                    ("completed", "Completed"),
                    ("delivered", "Delivered"),
                ],
                default="not started",
                max_length=20,
            ),
        ),
    ]
