# Generated by Django 5.1.3 on 2026-01-02 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Tamo", "0006_partin_assigned_to_alter_partin_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="partin",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
