# Generated by Django 5.1.3 on 2026-01-04 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Tamo", "0007_partin_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="partin",
            name="is_verified_in_stock",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="partin",
            name="last_inventory_check",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="partin",
            name="qr_code",
            field=models.ImageField(blank=True, null=True, upload_to="part_qrcodes/"),
        ),
    ]
