# Generated by Django 6.0.2 on 2026-02-11 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tamo', '0008_partin_is_verified_in_stock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partin',
            name='is_audit_approved',
            field=models.BooleanField(default=False, verbose_name='approved'),
        ),
    ]
