# Generated by Django 6.0.2 on 2026-02-11 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tamo', '0009_partin_is_audit_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='partin',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='parts_pdf/', verbose_name='PDF File'),
        ),
    ]
