# Generated by Django 6.0.2 on 2026-02-11 17:44

import Tamo.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tamo', '0010_partin_pdf_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partinlog',
            options={},
        ),
        migrations.AlterModelOptions(
            name='statushistory',
            options={},
        ),
        migrations.RemoveField(
            model_name='partin',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='partin',
            name='final_decision',
        ),
        migrations.RemoveField(
            model_name='partin',
            name='inspected_by_name',
        ),
        migrations.RemoveField(
            model_name='partin',
            name='inspection_date',
        ),
        migrations.RemoveField(
            model_name='partin',
            name='is_verified_in_stock',
        ),
        migrations.RemoveField(
            model_name='partin',
            name='last_inventory_check',
        ),
        migrations.RemoveField(
            model_name='partin',
            name='reason_of_removal',
        ),
        migrations.RemoveField(
            model_name='partinlog',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='statushistory',
            name='changed_by',
        ),
        migrations.AlterField(
            model_name='partin',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='my_assigned_parts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='partin',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to=Tamo.models.get_pdf_filename, verbose_name='PDF File'),
        ),
        migrations.AlterField(
            model_name='partinlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='partinlog',
            name='text',
            field=models.TextField(),
        ),
    ]
