# Generated by Django 6.0.2 on 2026-02-12 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tamo', '0012_statushistory_changed_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='partin',
            name='reason_for_removal',
            field=models.TextField(blank=True, null=True),
        ),
    ]
