# Generated by Django 6.0.2 on 2026-02-12 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tamo', '0013_partin_reason_for_removal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partin',
            old_name='reason_for_removal',
            new_name='reason_of_removal',
        ),
    ]
