# Generated by Django 6.0.2 on 2026-02-21 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tamo', '0015_partin_repair_completed_at_alter_partin_pdf_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='statushistory',
            name='is_warranty_claim',
            field=models.BooleanField(default=False, verbose_name='Is Warranty?'),
        ),
        migrations.AddField(
            model_name='statushistory',
            name='rejection_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statushistory',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
