# Generated by Django 6.0.2 on 2026-02-21 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tamo', '0016_statushistory_is_warranty_claim_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partin',
            name='delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='partin',
            name='is_delivered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='partin',
            name='is_warranty_claim',
            field=models.BooleanField(default=False, verbose_name='Is Warranty?'),
        ),
    ]
