# Generated by Django 6.0.2 on 2026-04-27 16:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tamo', '0017_partin_delivery_date_partin_is_delivered_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statushistory',
            name='is_warranty_claim',
        ),
        migrations.RemoveField(
            model_name='statushistory',
            name='rejection_date',
        ),
        migrations.RemoveField(
            model_name='statushistory',
            name='rejection_reason',
        ),
        migrations.AddField(
            model_name='partin',
            name='rejection_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='partin',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partin',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
